version: '3.7'

services:
    # MySQL
    db-mysql:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: codecamp-teamproject-db
        env_file: ./backend/.env.dev
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        restart: always

    # Redis
    db-redis:
        image: redis:latest
        container_name: codecamp-teamproject-redis
        ports:
            - 6379:6379
        restart: always

    # Elastic Search
    elasticsearch:
        image: elasticsearch:7.17.0
        container_name: codecamp-teamproject-elastic
        environment:
            discovery.type: single-node
        ports:
            - 9200:9200

    # Media Server
    media:
        build:
            context: ./media

        container_name: codecamp-teamproject-media

        ports:
            - 8500:8500

        env_file: ./media/.env.dev

        volumes:
            - ./media/src:/app/src
            - ./media/resource:/app/resource
            - ./media/dist:/app/dist

            - ./media/.env.dev:/app/.env

            - ./media/package.json:/app/package.json
            - ./media/yarn.lock:/app/yarn.lock
            - ./media/tsconfig.json:/app/tsconfig.json

        restart: always

    # NestJS
    backend:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: ./backend

        container_name: codecamp-teamproject-backend

        # Container Port 연결
        #   - host:container
        ports:
            - 3000:3000

        # 환경 변수 설정
        env_file: ./backend/.env.dev

        volumes:
            - ./backend/src:/app/src
            - ./backend/dist:/app/dist
            - ./backend/test:/app/test
            - ./backend/key:/app/key

            - ./backend/package.json:/app/package.json
            - ./backend/yarn.lock:/app/yarn.lock
            - ./backend/tsconfig.build.json:/app/tsconfig.build.json
            - ./backend/tsconfig.json:/app/tsconfig.json

            - ./backend/.env.dev:/app/.env

        # 재시작 설정
        restart: always
